openapi: 3.0.1
info:
  title: My API
  description: My API description
  version: 0.1.0
servers:
- url: http://localhost:8080
tags: []
paths:
  /api/v1/toilets:
    get:
      tags:
      - api
      summary: Retrieve a list of toilets near the specified latitude and longitude.
      description: Retrieve a list of toilets near the specified latitude and longitude.
      operationId: get-toilets
      parameters:
      - name: lat
        in: query
        description: Latitude of the location to search nearby toilets.
        required: true
        schema:
          type: string
      - name: lng
        in: query
        description: Longitude of the location to search nearby toilets.
        required: true
        schema:
          type: string
      - name: radius
        in: query
        description: Radius (in meters) to search for nearby toilets. Default is 5000
          meters.
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-v1-toilets1884267738"
              examples:
                get-toilets:
                  value: "[{\"id\":1,\"name\":\"강남역 공중화장실\",\"coord\":{\"lat\":37.4979,\"\
                    lng\":127.0286}},{\"id\":2,\"name\":\"역삼 문화센터 화장실\",\"coord\"\
                    :{\"lat\":37.5009,\"lng\":127.0372}},{\"id\":3,\"name\":\"선릉역\
                    \ 10번출구 화장실\",\"coord\":{\"lat\":37.5046,\"lng\":127.0485}},{\"\
                    id\":4,\"name\":\"삼성역 코엑스몰 화장실\",\"coord\":{\"lat\":37.5124,\"\
                    lng\":127.0592}},{\"id\":5,\"name\":\"을지로입구역 지하상가 화장실\",\"coord\"\
                    :{\"lat\":37.5661,\"lng\":126.9823}},{\"id\":6,\"name\":\"서울시청\
                    \ 시민청 화장실\",\"coord\":{\"lat\":37.5663,\"lng\":126.978}},{\"id\"\
                    :7,\"name\":\"홍대입구역 9번출구 화장실\",\"coord\":{\"lat\":37.5571,\"lng\"\
                    :126.9237}},{\"id\":8,\"name\":\"신촌역 공중화장실\",\"coord\":{\"lat\"\
                    :37.5595,\"lng\":126.9378}},{\"id\":9,\"name\":\"건대입구역 스타시티 화장\
                    실\",\"coord\":{\"lat\":37.54,\"lng\":127.0704}},{\"id\":10,\"\
                    name\":\"여의도 공원 화장실\",\"coord\":{\"lat\":37.5281,\"lng\":126.9225}}]"
  /api/v1/toilets/{id}:
    get:
      tags:
      - api
      summary: Retrieve detailed information about a specific toilet by its ID.
      description: Retrieve detailed information about a specific toilet by its ID.
      operationId: get-toilet-
      parameters:
      - name: id
        in: path
        description: Unique identifier of the toilet.
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/api-v1-toilets-id-522854228"
              examples:
                get-toilet-by-id:
                  value: "{\"id\":12,\"name\":\"서울역 2F 화장실\",\"address\":\"서울 중구 한\
                    강대로 405\",\"lat\":37.5547,\"lng\":126.9706,\"openHours\":\"06:00-23:00\"\
                    ,\"accessible\":true,\"diaper\":true,\"unisex\":false,\"avgRating\"\
                    :4,\"avgCleanliness\":4}"
                get-toilet-detail:
                  value: "{\"id\":1,\"name\":\"강남역 공중화장실\",\"coord\":{\"lat\":37.4979,\"\
                    lng\":127.0286},\"address\":\"서울 강남구 강남대로 390\",\"openAt\":\"\
                    2024-12-31T22:00:00Z\",\"closeAt\":\"2025-01-01T13:00:00Z\",\"\
                    accessible\":true,\"diaper\":true,\"unisex\":false}"
    post:
      tags:
      - api
      summary: Submit a review for a specific toilet by its ID.
      description: Submit a review for a specific toilet by its ID.
      operationId: post-toilet-review
      parameters:
      - name: id
        in: path
        description: Unique identifier of the toilet.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/api-v1-toilets-id-166555843"
            examples:
              post-toilet-review:
                value: "{\"stars\":4,\"comment\":null,\"likes\":{\"cleanliness\":false,\"\
                  toiletPaper\":false,\"waterPressure\":false,\"hotWater\":true,\"\
                  safety\":true}}"
      responses:
        "200":
          description: "200"
components:
  schemas:
    api-v1-toilets1884267738:
      type: array
      description: List of items
      items:
        type: object
        properties:
          coord:
            type: object
            properties:
              lng:
                type: number
                description: Longitude of the toilet.
              lat:
                type: number
                description: Latitude of the toilet.
          name:
            type: string
            description: Name of the toilet.
          id:
            type: number
            description: Unique identifier of the toilet.
        description: List of items
    api-v1-toilets-id-522854228:
      type: object
      properties:
        openHours:
          type: string
          description: Operating hours of the toilet.
        accessible:
          type: boolean
          description: Indicates if the toilet is accessible.
        address:
          type: string
          description: Address of the toilet.
        lng:
          type: number
          description: Longitude of the toilet.
        closeAt:
          type: string
          description: Closing time of the toilet.
        avgCleanliness:
          type: number
          description: Average cleanliness rating of the toilet.
        unisex:
          type: boolean
          description: Indicates if the toilet is unisex.
        coord:
          type: object
          properties:
            lng:
              type: number
              description: Longitude of the toilet.
            lat:
              type: number
              description: Latitude of the toilet.
        name:
          type: string
          description: Name of the toilet.
        avgRating:
          type: number
          description: Average overall rating of the toilet.
        diaper:
          type: boolean
          description: Indicates if the toilet has diaper facilities.
        id:
          type: number
          description: Unique identifier of the toilet.
        openAt:
          type: string
          description: Opening time of the toilet.
        lat:
          type: number
          description: Latitude of the toilet.
    api-v1-toilets-id-166555843:
      type: object
      properties:
        stars:
          type: number
          description: Star rating for the toilet (1 to 5).
        likes:
          type: object
          properties:
            safety:
              type: boolean
              description: Indicates if the reviewer felt safe using the toilet.
            waterPressure:
              type: boolean
              description: Indicates if the reviewer liked the water pressure.
            toiletPaper:
              type: boolean
              description: Indicates if the reviewer liked the availability of toilet
                paper.
            hotWater:
              type: boolean
              description: Indicates if the reviewer liked the availability of hot
                water.
            cleanliness:
              type: boolean
              description: Indicates if the reviewer liked the cleanliness of the
                toilet.
